production:
  environment: production
  production_environment: true

staging:
  auto_deploy_on: refs/heads/master
  required_contexts: ["build", "build2"]
  environment: staging
  production_environment: false

review:
  required_contexts: ["build", "build2"]
  environment: pr${{ pr }}
  transient_environment: true
  production_environment: false
